# dataset params
dataset:
  name: scape
  root_train: data/
  root_test: data/
  cache_dir: data/op_cache



# optimizer params
optimizer:
  lr: 1e-3
  b1: 0.9
  b2: 0.99
  decay_iter: 5
  decay_factor: 0.5

training:
  batch_size: 4
  epochs: 5

# fmap module params
fmap:
  n_fmap: 50  # number of eigenvectors used for fmap
  k_eig: 128  # number of eigenvectors used for diffusion
  n_feat: 128
  C_in: 3
  lambda_: 100
  resolvant_gamma: 0.5
  robust: False

# attention module params
attention:
  num_head: 4
  gnn_dim: 128
  ref_n_layers: 1
  cross_sampling_ratio: 0.7
  attention_type: normal

# overlap module
overlap:
  overlap_feat_dim: 32

# loss params
loss:
  w_fmap: 1
  w_acc: 1
  w_nce: 0
  nce_t: 0.07
  nce_num_pairs: 4096

# misc
misc:
  cuda: True
  device: 1
  checkpoint_interval: 5
  log_interval: 50
